language: python
python:
    - "3.7-dev"

sudo: false
cache: pip

before_install:
    - pip install docutils
script:
    - make -j

after_success:
  - test $TRAVIS_BRANCH = "master" &&
    make upload
