name: Codespell

on: [push, pull_request]

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          ignore_words_file: .github/codespell_ignore_words.txt
