name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetch all history so that last modified date-times are accurate

      - name: 🐍 Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3
          cache: "pip"

      - name: 👷‍ Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: 🔧 Build PEPs
        run: make pages -j$(nproc)

        # remove the .doctrees folder when building for deployment as it takes two thirds of disk space
      - name: 🔥 Clean up files
        run: rm -r build/.doctrees/

      - name: 🚀 Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch to deploy to.
          folder: build # Synchronise with build.py -> build_directory
          single-commit: true # Delete existing files
