name: Deploy to GitHub Pages

on: [push]

jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2

      - name: 🐍 Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: 🧳 Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      # Install dependencies and build PEPs using sphinx
      - name: 👷‍ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          make pages

      # Install dependencies and build PEPs using sphinx
      - name: 🔧 Build PEPs
        run: make pages

      - name: 🚀 Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
