name: Render PEPs

on: [push, pull_request, workflow_dispatch]

jobs:
  render-peps:
    name: Render PEPs
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch all history so that last modified date-times are accurate

      - name: 🐍 Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          cache: "pip"

      - name: 👷‍ Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: 🔧 Render PEPs
        run: make pages JOBS=$(nproc)

        # remove the .doctrees folder when building for deployment as it takes two thirds of disk space
      - name: 🔥 Clean up files
        run: rm -r build/.doctrees/

      - name: 🚀 Deploy to GitHub pages
        # This allows CI to build branches for testing
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages # The branch to deploy to.
          folder: build # Synchronise with build.py -> build_directory
          single-commit: true # Delete existing files

      - name: ♻️  Purge CDN cache
        if: github.ref == 'refs/heads/main'
        run: |
          curl -H "Accept: application/json" -H "Fastly-Key: $FASTLY_TOKEN" -X POST "https://api.fastly.com/service/$FASTLY_SERVICE_ID/purge_all"
        env:
          FASTLY_TOKEN: ${{ secrets.FASTLY_TOKEN }}
          FASTLY_SERVICE_ID: ${{ secrets.FASTLY_SERVICE_ID }}
